- name: update
  yum:
    name: '*'
    state: latest

- name: build hosts file
  lineinfile: dest=/etc/hosts regexp='.*{{ item }}$' line="{{ hostvars[item].ansible_eth1.ipv4.address }} {{item}}" state=present
  when: hostvars[item].ansible_eth1.ipv4.address is defined
  with_items: "{{ groups['all'] }}"

- name: disable selinux
  selinux: state=disabled

- name: disable of selinux - now
  command: setenforce 0

- name: Create /etc/pwx
  file: path=/etc/pwx state=directory

- name: Install px config
  copy: src=config.json owner=root group=root dest=/etc/pwx/config.json force=no

- name: install utility programs
  yum: name={{ item }} state=present disable_gpg_check=yes
  with_items:
    - wget
    - ntp
    - screen
    - epel-release
    - vim
    - iptables
    - iptables-utils
    - iptables-services
    - ncurses-term
    - docker
    - etcd

- name: update etcd config
  lineinfile: dest=/etc/etcd/etcd.conf regexp='^ETCD_LISTEN_CLIENT_URLS=' line='ETCD_LISTEN_CLIENT_URLS=http://{{ ansible_eth1.ipv4.address }}:2379,http://127.0.0.1:2379' state=present

- name: enable services
  service: name={{ item }} state=started enabled=yes
  with_items:
    - docker
    - ntpd
    - etcd

- name: Pulling pximage
  command: docker pull {{ pximage }}

- name: determine if it is running already
  command: docker inspect px-dev
  register: inspect_result
  ignore_errors: True

- name: stop px-dev
  command: docker stop px-dev
  when: inspect_result is succeeded

- name: rm px-dev
  command: docker rm px-dev
  when: inspect_result is succeeded

- name: Installing and starting Px container. This may take a while
  command: docker run --name px-dev -d --net=host --privileged=true -e PORTWORX_ENABLE_SDK=yes -v /mnt:/mnt:shared -v /run/docker/plugins:/run/docker/plugins  -v /var/lib/osd:/var/lib/osd:shared -v /dev:/dev -v /etc/pwx:/etc/pwx -v /opt/pwx/bin:/export_bin:shared -v /var/run/docker.sock:/var/run/docker.sock  -v /var/cores:/var/cores -v /usr/src:/usr/src -v /lib/modules:/lib/modules -v /opt/pwx:/opt/pwx -v /etc/systemd/system:/etc/systemd/system -v /host_proc/1/ns:/host_porc/1/ns {{ pximage }}

- name: Waiting for system to be online
  wait_for: timeout=600 port=9001

